import { Placeholder } from "@angular/compiler/src/i18n/i18n_ast";

const tsv_str = `	Name	NameCh	Affiliations	Headshot link	ImgFileName	Description link	Description	Networking(lunch or breakfast)	Links	Email	Parking
Keynote	Laura Sepp-Lorenzino		Chief Scientific Officer, Intellia Therapeutics	Laura headshot	laura-sepp.jpg	Laura shortbio	<p>Dr. Laura Sepp-Lorenzino is Executive Vice President, Chief Scientific Officer at Intellia Therapeutics, a company developing curative genome editing treatments to positively transform the lives of people with genetic diseases. She oversees all drug research across in vivo and engineered cell therapy areas at Intellia. Previously, she was VP, Head Nucleic Acid Therapies at Vertex Pharmaceuticals and before that, VP, Entrepreneur-in-Residence at Alnylam, a leader in the development of RNAi Therapeutics. At Alnylam, Laura was responsible for the Hepatic Infectious Disease Strategic Therapeutic Area, championed Extra Hepatic siRNA Delivery internally, and via a number of collaborations, was active in licensing and partnering. Before joining Alnylam, she spent 14 years at Merck & Co., having most recently served as Executive Director and Department Head, RNA Therapeutics Discovery Biology. In this role, Laura was responsible for identification and optimization of siRNAs and delivery vehicles, advancement of preclinical candidates, and development of an siRNA-conjugate platform to expand the repertoire of tissues accessible to in vivo siRNA delivery. Prior to her work with RNAi, Laura led the Cancer Research Department at Merck West Point, where she managed oncology drug discovery and development. She began her career in academia, as an Assistant Lab Member and Assistant Attending Molecular Biologist at Memorial Sloan-Kettering Cancer Center. Laura received her Professional Degree in Biochemistry from the University of Buenos Aires, and her M.S. and Ph.D. in Biochemistry from New York University.</p>		https://www.linkedin.com/in/laurasepplorenzino/
Keynote	Samir Mitragotri		Core Faculty, Wyss Institute at Harvard University	Samir headshot	Samir-Mitragotri-Listing-Image.jpg	samir shortbio	<p>Professor Mitragotri's research is focused on drug delivery. His research has advanced fundamental understanding of biological barriers and has led to the development of new materials as well as technologies for the treatment of various ailments including diabetes, cancer, skin diseases, multiple sclerosis, and infections, among others. Many of his inventions have advanced to clinical technologies. His research has led to a number of start-up companies. At the same time, the fundamental knowledge developed through his research has advanced the understanding of the biology of barriers in the human body. Prof. Mitragotri has pioneered novel technologies using ultrasound and ionic liquids to enable transdermal delivery of proteins, peptides, and siRNA. He has also developed novel technologies including ionic liquids for oral delivery of proteins such as insulin and other peptides. Prof. Mitragotri has invented systems that make use of synthetic carriers hitchhiking on natural cells such as red blood cells, macrophages, neutrophils, T cells, and NK cells for targeted delivery of drugs and cells.</p>  <p>Professor Mitragotri is the Hiller Professor of Bioengineering and Hansjörg Wyss Professor of Biologically Inspired Engineering at Harvard University. He has authored over 400 publications, is an inventor on over 225 issued/pending patents, and he has given over 500 invited lectures. He is an elected member of the National Academy of Engineering, National Academy of Medicine and National Academy of Inventors. He is also an elected fellow of AAAS, CRS, BMES, AIMBE, and AA PS. He received BS in Chemical Engineering from the Institute of Chemical Technology, India and PhD in Chemical Engineering from the Massachusetts Institute of Technology.</p>		https://wyss.harvard.edu/team/core-faculty/samir-mitragotri/
Keynote					yuk-cheung-chris-chan.jpeg
Trending Topic	Rakesh Dixit		Cofounder, President and CSO, Regio Biosciences		Rakesh-Dixit.jpg				https://www.linkedin.com/in/rakesh-dixit-ph-d-dabt-8979309/
Trending Topic	Yvonne (Yi-Yang) Lau		Executive Director, Daiichi Sankyo	Yvonne headshot	Yvonne-Lau_headshot.jpg	Yvonne ShortBio	<p>Yvonne Lau, PhD, is currently an Executive Director and Oncology Portfolio Lead within the Quantitative Clinical Pharmacology Department of the Global Precision Medicine function at Daiichi Sankyo, Inc. Her group provides strategic clinical pharmacology and pharmacometrics support to oncology programs, spanning early to late stages, across different molecule modalities (small molecules, mAbs, ADCs). Before joining Daiichi Sankyo, Yvonne held increasingly responsible roles in the Oncology Clinical Pharmacology departments at Janssen and Novartis. Earlier in her career, she worked in the DMPK and Clinical Pharmacology groups at Amgen and MedImmune, contributing across multiple therapeutic areas. Yvonne earned her Ph.D. in Biopharmaceutical Sciences from the University of California, San Francisco. She has over 17 years of industry experience in the development of small molecules and biologics, along with extensive experience with global regulatory interactions, having contributed to a number of successful filings.</p>		https://www.linkedin.com/in/yvonne-yi-yang-lau-555974a/
Trending Topic	Ting-Hui Wu		Senior Medical Director, Mythic therapeutics		Ting-Hui-Wu.jpg				https://www.linkedin.com/in/ting-hui-wu-md-msc-ab535733/
Trending Topic	Yuk-Cheung (Chris) Chan		Senior Scientist, AstraZeneca	https://docs.google.com/document/d/1aRlzULLoCNFtsQzuZBtt3scJwmUGtjpH/edit?usp=sharing&ouid=104941311771459350525&rtpof=true&sd=true	yuk-cheung-chris-chan.jpeg	https://docs.google.com/document/d/1aRlzULLoCNFtsQzuZBtt3scJwmUGtjpH/edit?usp=sharing&ouid=104941311771459350525&rtpof=true&sd=true	<p>Chris Chan was born and raised in Hong Kong. He received PhD in Chemistry under the supervision of Prof. Ying-Yeung Yeung from The Chinese University of Hong Kong in 2019. His graduate research focused on application of non-covalent interaction in organocatalysis. Motivated by the power of small molecule, he joined Prof. Scott Miller’s group as a Postdoctoral Associate in Yale University, where he has developed new peptide catalysis for heterocycle functionalization with high generality. Chris was also a member in Center for Genetically Encoded Materials (NSF Center) for studying beta-amino acid effect in ternary complex stability. He started his industrial career in Eisai, then moved to AstraZeneca in 2024 as Senior Scientist to work on Antibody-Drug-Conjugate (ADC) and other targeted delivery. Chris’s research has been published in J. Am. Chem. Soc., Angew. Chem. Int. Ed., ACS Cent. Sci. and Org. Lett.</p>		https://www.linkedin.com/in/yuk-cheung-chan-7b9630188/
Panel#1 Business Development (confirmed)	Gina Song		Senior Director of Business Development at Schrödinger		gina-song.jpeg	https://docs.google.com/document/d/1iI9fdyAYeXFri1ydfOsELXquecfTsVNKhl1vEHLeAxI/edit	<p>Gina is the Senior Director of Business Development at Schrödinger, bringing over eight years of experience in the biotech and biopharma industry. With a strong track record in both in-licensing and out-licensing deals, Gina has played a pivotal role in advancing strategic partnerships of Schrödinger.</p>  <p>Gina holds a bachelor’s and master’s degree in biology and biochemistry from Tsinghua University as well as an MBA from UC Berkeley. Before transitioning to the biotech sector, Gina spent six years in investment banking. She is passionate about the intersection of business development and healthcare and is dedicated to accelerating the development of new drugs to benefit patients worldwide.</p>		https://www.linkedin.com/in/duncan-hamish-wright-089700/
Panel#1 Business Development (confirmed)	Po-Jen (Will) Yen	顏伯任	Head of Search, Evaluation & Licensing - Voyager Therapeutics		Po-Jen_Yen.jpg	https://docs.google.com/document/d/1iI9fdyAYeXFri1ydfOsELXquecfTsVNKhl1vEHLeAxI/edit	<p>As a core member of the Corporate and Business Development team at Voyager Therapeutics, Will has led increasingly important business development activities and played significant roles in corporate development to facilitate company growth, driving strategy, competitive intelligence, as well as supporting research and development with both his science and business expertise. Prior to Voyager, Will worked at Biogen Corporate Strategy, where he analyzed neurodegenerative disease space with a comprehensive approach to identify trends and barriers of the field, thereby informing the company's investment opportunities and long-term strategy. A research scientist by training, Will started his career at Agios, after receiving a PhD in Virology at Harvard University, a Master in Biotechnology at University of Pennsylvania, and a Bachelor in Zoology at National Taiwan University.</p>		https://www.linkedin.com/in/willyen/
Panel#1 Business Development (confirmed)	Irene Lau		VP Business Development - Intellia Therapeutics		irene-lau.jpeg	https://docs.google.com/document/d/1iI9fdyAYeXFri1ydfOsELXquecfTsVNKhl1vEHLeAxI/edit?usp=sharing	<p>Irene Lau is the Vice President of Business Development at Intellia Therapeutics, where she leads the development of the Company's cell therapy partnering strategy and drives strategic partnering initiatives to advance its innovative engineered cell therapy platforms. Prior to Intellia, Irene held a leadership role in portfolio strategy at Alnylam Pharmaceuticals, where she spearheaded the development of the company's long-range plan. As part of the business development team at Alnylam, she also played an integral role in major alliances, including an $800M partnership with Regeneron. With over 15 years of experience spanning biotech business development, corporate strategy, and Wall Street equity research, Irene brings a unique blend of strategic acumen and deal-making expertise to drive the growth and success of cutting-edge biotech companies.</p>		https://www.linkedin.com/in/irene-lau-b33b8612/
Panel#1 Business Development (confirmed)	JM Lee		Transactions lead in the Corporate Development/ BD department at Novo Nordisk		jm-lee.jpeg	https://docs.google.com/document/d/1iI9fdyAYeXFri1ydfOsELXquecfTsVNKhl1vEHLeAxI/edit	<p>JM is a transactions lead in the Corporate Development/ BD department at Novo Nordisk, spending most of her time on in-licensing and collaboration negotiations. She is the main business partner to Novo's Bio Innovation Hub, a Boston-based research unit tasked with collaborating with unique platforms to discover novel therapeutics. Prior to Novo Nordisk, JM was a BD lead at Takeda's Center for External Innovation, Sanofi's global transactions, and Bioverativ (spin-out of Biogen acquired by Sanofi). She started her career as a consultant at McKinsey & Co. in the pharmaceuticals & medical products practice after her PhD in Chemistry at MIT. JM holds her Bachelor's in Biochemistry and Mathematics from Bates College.</p>		https://www.linkedin.com/in/jm-lee-02118/
Panel#2 Biotech Entrepreneurship	Robert Ang		President and CEO - VOR Bio	Robert_headshot	robert-ang.jpeg	Robert short bio	<p>Robert Ang, MBBS, MBA, is President and CEO at Vor Bio, a publicly-traded company working on next-generation hematopoietic stem cell transplants. Vor uses stem cells, gene editing, and CAR-T technologies with the hope of curing liquid tumors. Vor has raised over $470M in gross proceeds from private and public financing and has translated the science into two clinical programs treating patients with acute myeloid leukemia and myelodysplastic syndrome.</p>  <p>Prior to Vor, Robert had operational experience focused on strategy and business development roles at Neon Therapeutics (now BioNTech), Bavarian Nordic, and Cadence Pharmaceuticals (now Mallinckrodt). Robert also had biotech venture capital experience at Frazier Healthcare Ventures where he invested in companies such as Incline Therapeutics (now Novartis) and Alnara Pharmaceuticals (now Eli Lilly), and strategy consulting experience at the Boston Consulting Group. His clinical practice centered around soft tissue surgery with an emphasis around solid organ transplants. He received his medical degree at the University of Western Australia and has an MBA with Honors from Columbia Business School. Robert also serves as an independent director at the early-stage cancer immunotherapy company Enara Bio, the Alliance for Regenerative Medicine, and the Healthcare and Pharmaceutical Management Advisory Board of Columbia Business School.</p>		https://www.linkedin.com/in/robert-ang-069746/
Panel#2 Biotech Entrepreneurship	Daniel Fisher		Co-Founder, President and CEO - TEVARD Biosciences		Daniel-Fischer.jpg		<p>Daniel Fischer co-founded Tevard Biosciences to develop gene therapy approaches to cure Dravet Syndrome — a disease that affects his daughter Natasha — and other rare diseases not amenable to traditional gene therapy approaches. He brings extensive management and entrepreneurial expertise. Daniel has been a management consultant to Fortune 500 companies with several top-tier consultancies, including A.T. Kearney and Arthur D. Little. Daniel worked at the Massachusetts Institute of Technology with industry, academic researchers, and startups in advancing the state-of-the-art in multiple disciplines, including: AI/machine learning, biotechnology, nanotechnology, IoT, and innovation management. Daniel was the founder and CEO of Intellimedix which he co-founded to develop and implement a platform for personalized medicine. In 2000 he co-founded and managed Comerxia, a company that was featured in TIME magazine as the leading solution for international ecommerce.</p>		https://www.linkedin.com/in/daniel-fischer-2b1a363/
Panel#2 Biotech Entrepreneurship	Sabrina Yang		Co-Founder and Chief Innovation Officer - Empress Therapeutics		sabrina-yang.jpeg				https://www.linkedin.com/in/sabrina-yang-a0438b53/
Panel#2 Biotech Entrepreneurship	Yen-Ming Hsu		Founder and CEO - AB Biosciences		Yen-Ming_Hsu.jpeg				https://www.linkedin.com/in/yen-ming-hsu-85b08523/
Panel#3 Translational Science	Yi-Li Min	閔譯立	Associate Director @ Vertex Cell and Genetic Therapies | Gene Editing & Nonclinical Research		Academia_Yi-Li_Min.jpg				https://www.linkedin.com/in/yilimin/
Panel#3 Translational Science	Emily Hsiue	薛涵中	Senior Medical Director, Early Clinical Development, Oncology, AZ		emily-hsiue.jpeg				https://www.linkedin.com/in/emily-hsiue-117a32ba/
Panel#3 Translational Science
Panel#3 Translational Science
Panel#3 Translational Science (Back up)	Magaret Wey	魏嘉英	Director of Global Medicines Development, AZ		Margaret_Wey.jpg
Panel#4 Advanced Bioprocessing & CDMO	Mark Brader		Fellow, Technical Developement, Moderna	Mark headshot and short bio	Mark-Brader.jpg	Mark headshot and short bio	<p>Dr. Mark Brader, PhD, is a Research Fellow and group leader in the Technical Development division at Moderna, responsible for mRNA-lipid nanoparticle characterization and biophysical analysis. He is a formulations and biophysical development scientist with over 20 years’ experience leading technical teams. His work reflects a longstanding curiosity about the molecular pharmaceutics of higher-order structures and the impact of non-covalent phenomena on product quality attributes. He has contributed to elucidating key fundamentals of mRNA-lipid nanoparticles and was part of the team that developed the Moderna Covid-19 vaccine during the pandemic. As part of his leadership role at Moderna, he also serves as People Champion for scientific excellence, engagement, wellness and belonging within Analytical Development. In previous roles within the pharmaceutical biotechnology industry, Dr. Brader has worked extensively on drug product development of insulin analogs, GLP-1 peptides, enzymes, and monoclonal antibodies. On a personal note, Dr. Brader grew up in New Zealand where he conducted his scientific training at Massey University, graduating with a PhD in Chemistry. Prior to starting his industrial career as a Senior Pharmaceutical Scientist at Eli Lilly and Company, he held postdoctoral positions at the University of California at Riverside, Department of Biochemistry and at Rutgers University, Department of Chemistry.</p>		https://www.linkedin.com/in/bioactive/
Panel#4 Advanced Bioprocessing & CDMO	Nicole Payton		Director, Drug Product Development, AstraZeneca		nicole-payton.jpeg				https://www.linkedin.com/in/nicole-payton-26934098/
Panel#4 Advanced Bioprocessing & CDMO
Panel#4 Advanced Bioprocessing & CDMO
Lunch - Industry
Lunch - Industry
Lunch - Industry
Lunch - Industry
Lunch - Industry
Lunch - Academic	Hsiao-Ying Monica Wey	魏曉英			Academia_Wey.jpg				https://weylab.martinos.org	hsiaoying.wey@mgh.harvard.edu
Lunch - Academic	Meng-Ju Wu 	吳孟儒			Meng-Ju_Wu.jpg
Lunch - Academic	Ming-Ru Wu	吳名儒			Academia_Ming-Ru_Wu.jpg
Lunch - Academic		蔡孟勳
Lunch - Academic	Yen-Cheng Chen	陳晏誠
Breakfast (confirmed)	Hsiao-Ling Hung	洪筱玲	President, Taiwanese American Association of Biotechnology (TAAB)		Hsiao-Ling_Hung.jpeg
Breakfast
Breakfast
Breakfast
Breakfast
Breakfast
Breakfast
Breakfast
Breakfast
Breakfast											`;

const tsv_array = tsv_str
	.split('\n')
	.map(el => el.split('\t'))
	.filter(el => el[1])
	.map(el => {
		return {
			'name': el[1].trim() || null,
			'nameCh': el[2] || null,
			'affiliations': el[3] ? el[3].split(';') : [],
			'imgFileName': el[5] || 'placeholder.jpg',
			'links': el[9] ? el[9].split(';') : [],
			'description': el[7] || ''
		};
	});

const tsv_dict = {};

tsv_array.forEach(el => {
	el.name.trim() in Object.keys(tsv_dict)
		? false
		:  tsv_dict[el.name.trim()] = el;
});

export const speakersObj = tsv_dict;
