import { Placeholder } from "@angular/compiler/src/i18n/i18n_ast";

const tsv_str = `	Name	NameCh	Affiliations	ImgFileName	Description	happyHour	Links
Keynote	George Church		Professor, Harvard and MIT	George.jpeg	<p>George leads Synthetic Biology at the Wyss Institute, where he oversees the directed evolution of molecules, polymers, and whole genomes to create new tools with applications in regenerative medicine and bio-production of chemicals. Among his recent work at the Wyss is development of a technology for synthesizing whole genes, and engineering whole genomes, far faster, more accurate, and less costly than current methods. George is widely recognized for his innovative contributions to genomic science and his many pioneering contributions to chemistry and biomedicine. In 1984, he developed the first direct genomic sequencing method, which resulted in the first genome sequence (the human pathogen, H. pylori). He helped initiate the Human Genome Project in 1984 and the Personal Genome Project in 2005. George invented the broadly applied concepts of molecular multiplexing and tags, homologous recombination methods, and array DNA synthesizers. His many innovations have been the basis for a number of companies including Editas (Gene therapy); Gen9bio (Synthetic DNA); and Veritas Genetics (full human genome sequencing).</p><p>George is Professor of Genetics at Harvard Medical School and Professor of Health Sciences and Technology at Harvard and the Massachusetts Institute of Technology (MIT). He is Director of the U.S. Department of Energy Technology Center and Director of the National Institutes of Health Center of Excellence in Genomic Science. He has received numerous awards including the 2011 Bower Award and Prize for Achievement in Science from the Franklin Institute and election to the National Academy of Sciences and Engineering.</p>		https://wyss.harvard.edu/team/core-faculty/george-church/
Keynote	Liz Kwo		Chief Medical Officer, Everly Health	Liz.jpg	<p>Dr. Liz Kwo is an experienced healthcare executive specialized in building and scaling digital health products, leveraging predictive and prescriptive analytics to improve outcomes. Her current role at Everly Health is to create personalized and quality diagnostic driven care (test to treat) at home. Prior to Everly Health, she was the Deputy Chief Clinical Officer at Anthem (Elevance), creating automated business models for UM/CM/DM (prior authorization, member engagement, care interventions, provider integrated models) with AI to reduce total medical cost and improve care. Her product strategy team drove innovation across government and commercial businesses. She has worked in remote patient monitoring for Medtronic, American Well as the VP of Provider Networks, and is an active angel investor in the healthcare community, with an interest in technology-enabled healthcare delivery. She founded multiple venture-backed companies in educational technology (New Pathway acquires by CVC private equity, 2014), digital healthcare (InfiniteMD acquired by Consumer Medical, 2020) and is passionate about creating tailored experiences for patients and building on-demand data driven insights to support Medicare, Medicaid, and employer clients.</p><p>Dr. Kwo’s experience spans healthcare technology product development and commercialization, P&L management, B2B/B2C marketing & sales, strategic partnerships, & post-merger integration. A non-executive board member of public and private companies and a practicing physician in urgent and occupational medicine at Cambridge Health Alliance Harvard Medical School teaching hospital, Dr. Kwo’s clinical expertise as a Faculty Lecturer at Harvard Medical School allows her to translate ideas from bench to bedside. She continues to practice medicine in urgent care and holds an active medical license in Massachusetts.</p><p>Dr. Kwo has an MD from Harvard Medical School, MBA from Harvard Business School, MPH from Harvard TH Chan School of Public Health, and a BA from Stanford University. She completed her residency at Harvard Preventive Care and is Board Certified in Preventive Care and Occupational Medicine.</p><p>Check out Dr. Kwo’s new book about leading the digital health revolution:<a href="www.drlizkwo.com">Digital MD</a></p>		https://www.linkedin.com/in/lizkwo/
Trending	Yi-Hsiang Hsu		Co-Director Geriomics Program, Marcus Institute for Aging Research, Harvard Medical School	yi-hsiang-hsu.jpeg	<p>Dr. Hsu has led multiple large-scale whole genome sequencing (WGS), genome-wide association study (GWAS) and Multi-OMICS projects on metabolic-relevant disorders, cardiovascular disorders, musculoskeletal disorders and neuropsychiatric disorders. He has published 120 papers about human genetics and statistical genetics and is regarded as one of the leading experts in the field of using sophisticated statistical genetics and AI deep-learning machine-learning to conduct advanced statistical analysis.</p>	Yes/No	https://www.linkedin.com/in/yi-hsiang-hsu-379b2839/
Trending	Bin Li		Director of Computational Biology at Takeda	Bin_li.jpeg	<p>Dr. Li leads a computational biology team that provides translational bioinformatics support across oncology, GI, NS, and rare disease therapeutic areas. The team supports Takeda's clinical programs by being accountable for omics clinical biomarker data QC, processing, and clinical database deposition. They collaborate with translational science, biostatistics, clinical pharmacology, and other teams to support clinical programs' exploratory analysis and translational research efforts. Additionally, the team utilize AI/ML approaches for drug sensitivity predictions.</p>	Yes/No	https://www.linkedin.com/in/bin-li-b6410b4/
lunch	Mong-Hsun Tsai	蔡孟勳	Professor, NTU	Mong-Hsun_Tsai.jpg		Yes/No	https://www.linkedin.com/in/mong-hsun-%E8%94%A1%E5%AD%9F%E5%8B%B2-tsai-4a509999/
lunch	Chris Chiu		Assistant Professor, University of Pittsburgh	Yu-Chiao_Chiu.png	<p>Dr. Yu-Chiao (Chris) Chiu is an Assistant Professor of Medicine at the Division of Hematology/Oncology and a faculty member of the Cancer Therapeutics Program at the UPMC Hillman Cancer Center at the University of Pittsburgh. His research interests include bioinformatics, machine learning, cancer genomics, and pharmacogenomics. The goal of his laboratory is to systematically model genomics and pharmacogenomics to gain a better understanding of cancer biology and improve cancer therapy. Dr. Chiu has been honored with the prestigious NIH/NCI K99/R00 Pathway to Independence Award for his work in developing deep learning methods to predict the responses of cancer cells to treatments. Furthermore, he has received research grants from the Fund for Innovation in Cancer Informatics, Pittsburgh Liver Research Center, UPMC Hillman Cancer Center Developmental Pilot Program, and San Antonio Life Sciences Institute. To date, Dr. Chiu has published over 100 journal articles and conference articles/abstracts. He is an active member of the bioinformatics community and has chaired sessions in the IEEE BIBM 2021 and ICIBM 2022 conferences. Currently, he serves as the Educational Activity Chair of the upcoming IEEE-EMBS International Conference on Biomedical and Health Informatics (BHI) 2023. For further details, please visit https://chiu-lab.org/.</p>	Yes/No	https://chiu-lab.org/
lunch	Kun-Hsing Yu		Assistant Professor, Harvard Medical School	Kun-Hsing_Yu.jpg	<p>Kun-Hsing "Kun" Yu, M.D, Ph.D. is an Assistant Professor in the Department of Biomedical Informatics at Harvard Medical School. He developed the first fully automated algorithm to extract thousands of features from whole-slide histopathology images, discovered the molecular mechanisms underpinning the microscopic phenotypes of tumor cells, and successfully identified previously unknown cellular morphologies associated with patient prognosis. His lab integrates cancer patients' multi-omics (genomics, epigenomics, transcriptomics, and proteomics) profiles with quantitative histopathology patterns to predict their clinical phenotypes. Dr. Yu's research interests include quantitative pathology, machine learning, and translational bioinformatics.</p>	Yes/No	https://yulab.hms.harvard.edu/yu/
lunch	Wan-Ping Lee		Assistant Professor, University of Pennsylvania	Wan-Ping_Lee.jpg	<p>Born, raised, and educated in Taiwan, Wan-Ping Lee is currently an Assistant Professor of Pathology and Laboratory Medicine in the Research track at Perelman School of Medicine at the University of Pennsylvania. Wan-Ping Lee also serves as Associate Director of IT of The National Institute on Aging Genetics of Alzheimer’s Disease Data Storage Site (NIAGADS) and Co-Chair of the Alzheimer’s Disease Sequencing Project (ADSP) Structural Variant (SV) Working Group. Wan-Ping previously worked at the Jackson Laboratory for Genomic Medicine and spearheaded a research collaboration in China. During her time in Xian, China, she gained valuable experience working in an international research setting. Prior to the Jackson Laboratory, Wan-Ping was the leader of the R&D team at Seven Bridges Genomics, based in Boston and London. Her experience in industry has been instrumental in her continued success in academia.</p>	Yes/No	https://www.linkedin.com/in/wan-ping-lee-bba68331
lunch	Hui-Hao Lin		Assistant Professor, UPSTATE	
lunch	Jack Hsu		Assistant Professor, Rutgers New Jersey Medical school	Jack_Hsu.jpg	<p>Dr. Jack Hsu received his BS and MS from National Taiwan University. He obtained his Ph.D. from Duke University in Biochemistry, where he discovered and characterized translational regulation and RNA localization in Dr. Christopher Nicchitta’s lab. Jack did his postdoctoral training at Yale University in the groups of Drs. Peter Cresswell and Maudry Laurent-Rolle, where investigated translational regulation in innate immunity and SARS-CoV-2 infection. Jack received Ruth L. Kirschstein National Research Service Awards (T32), Cancer Research Institute’s highly regarded Irvington Postdoctoral Fellowship, and a K22 Career Transition Award from the NIAID. Jack started his research program at Rutger New Jersey Medical School in Newark in the Summer of 2023. His long-term goal is to dissect the mechanisms of translational regulation in viral infection and during the innate antiviral responses.</p>
`;

const tsv_array = tsv_str
	.split('\n')
	.map(el => el.split('\t'))
	.filter(el => el[1])
	.map(el => {
		return {
			'name': el[1].trim() || null,
			'nameCh': el[2] || null,
			'affiliations': el[3] ? el[3].split(';') : [],
			'imgFileName': el[4] || 'placeholder.jpg',
			'links': el[7] ? el[7].split(';') : [],
			'description': el[5] || ''
		};
	});

const tsv_dict = {};

tsv_array.forEach(el => {
	el.name.trim() in Object.keys(tsv_dict)
		? false
		:  tsv_dict[el.name.trim()] = el;
});

export const speakersObj = tsv_dict;
